### PR TITLE
`minchunksize` + `split::SplitStrategy` (new default)

### PR DESCRIPTION
**Pull request by carstenbauer**
Implements the `minchunksize` option.

### CODE REVIEW

**Comment by carstenbauer** [comment]
With the changes I made we at least get

```julia-repl
julia> function f(x; n=nothing, size=nothing)
           s = zero(eltype(x))
           for inds in chunks(x; n=n, size=size)
               for i in inds
                   s += x[i]
               end
           end
           return s
       end
f (generic function with 1 method)

julia> @benchmark f($(rand(10^3)); n=4) samples=1 evals=1
BenchmarkTools.Trial: 1 sample with 1 evaluation.
 Single result which took 959.000 ns (0.00% GC) to evaluate,
 with a memory estimate of 0 bytes, over 0 allocations.

julia> VERSION
v"1.10.5"
```

**Comment by lmiq** [comment]
Honestly I find that magical... but if it works, it works. Its fine for me.

**Comment by carstenbauer** [comment]
It's not magical: Julia specializes on types (also those of keyword arguments). Hence it can figure out from the function call what kind of splitter we use etc. This is different if you specify `split` as a `Symbol` because then Julia has to look at **values** to deduce the splitter type etc.

**Comment by lmiq** [comment]
Ah, of course, at first I didn't realize that passing a symbol would still allocate.

**Comment by lmiq** [comment]
I guess we need to document the passing of types then. Maybe remove the symbol option in a 3.0.

**Comment by carstenbauer** [comment]
I'm doing it. Let me make a few more changes and then you can make a pass.

**Comment by carstenbauer** [comment]
Alright, feel free to review. Tests should all pass.

**Pull request merged**
